language: node_js
os:
  - linux
env:
  - CXX=g++-4.8
node_js:
  - 6
  - 7
  - 8
notifications:
  recipients:
    - kubying@qq.com
    
  email:
    on_success: change
    on_failure: always
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_script:
     - pwd
script:
     - bash ./test/multi-nodes/multiNodes.sh

